// Code generated by "stringer -type=ApplyWhen"; DO NOT EDIT

package blocks

import "fmt"

const _ApplyWhen_name = "ApplyBeforeApplyAfterApplyOn"

var _ApplyWhen_index = [...]uint8{0, 11, 21, 28}

func (i ApplyWhen) String() string {
	if i < 0 || i >= ApplyWhen(len(_ApplyWhen_index)-1) {
		return fmt.Sprintf("ApplyWhen(%d)", i)
	}
	return _ApplyWhen_name[_ApplyWhen_index[i]:_ApplyWhen_index[i+1]]
}
