// Code generated by "stringer -type=Term"; DO NOT EDIT

package blocks

import "fmt"

const _Term_name = "PreTermQuotesTermContentTermPostTermSepTermScopeTermNumTerms"

var _Term_index = [...]uint8{0, 7, 17, 28, 36, 43, 52, 60}

func (i Term) String() string {
	if i < 0 || i >= Term(len(_Term_index)-1) {
		return fmt.Sprintf("Term(%d)", i)
	}
	return _Term_name[_Term_index[i]:_Term_index[i+1]]
}
