// Code generated by "stringer -type=ParamType"; DO NOT EDIT

package inspect

import "fmt"

const _ParamType_name = "ParamTypeUnknownParamTypeCommandParamTypeArrayParamTypePrimParamTypeBlob"

var _ParamType_index = [...]uint8{0, 16, 32, 46, 59, 72}

func (i ParamType) String() string {
	if i < 0 || i >= ParamType(len(_ParamType_index)-1) {
		return fmt.Sprintf("ParamType(%d)", i)
	}
	return _ParamType_name[_ParamType_index[i]:_ParamType_index[i+1]]
}
